inherit_from:
- https://everydayhero.github.io/styleguide/rubocop.yml

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueModifier:
  Enabled: false

# 1.8 compatible :(
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# 1.8 compatible :(
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma
